version: "3.9"
services:
  react:
    image: node
    entrypoint: /bin/sh
    working_dir: /home/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./
        target: /home/app
    tty: true